services:
  - type: web
    name: pooreyoutuber-combined-service
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: NODE_VERSION
        value: "20.0.0" # Stabilize node version
        
